### ISSUE TITLE
I found a page that crashes the downloader...

### ISSUE THREAD

**Issue by rdragonrydr** [JimmXinu/FanFicFare#515] opened 2020-07-21 02:55 UTC
Sorry to bother you _again_...

I was attempting to archive a story on RoyalRoad when I got a strange error about a missing item on chapter 39 of this story.
On visiting the page, it apparently only has an author's note with a very, very long link in it, seemingly due to a formatting error.

https://www.royalroad.com/fiction/26534/vainqueur-the-dragon/chapter/428050/39-the-ballad-of-jolie-dragon

Are you able to add a patch for this sort of thing, or a "skip/resume" option? It downloaded all the other (preceding, anyway) chapters before failing, so the ability to bypass a corrupted chapter for manual fill-in could be useful.

**Comment by JimmXinu** [comment] 2020-07-21 03:24
I'll look at that tomorrow.  

There is already a setting for continuing on despite chapter errors:
```
## Because some adapters can pull chapter URLs from human posts, the
## odds of errors in the chapter URLs can be higher for some
## sites/stories.  You can set continue_on_chapter_error:true to
## continue on after failing to download a chapter and instead record
## an error message in the ebook for that chapter.
continue_on_chapter_error:true

## Append this to chapter titles that errored.  Only used with
## continue_on_chapter_error:true
## Set empty to not mark failed chapters.
chapter_title_error_mark:(CHAPTER ERROR)
```

**Comment by rdragonrydr** [comment] 2020-07-21 04:07
What does "not marking" the chapter do?
And does the parenthesized portion get set to the chapter that failed, or
is that actually the parameter?

**Comment by JimmXinu** [comment] 2020-07-21 15:44
The failed chapter text is replaced by an error message.

`chapter_title_error_mark` says right on it: `Append this to chapter titles that errored.`  Otherwise, you wouldn't have any indicator of a failed chapter without looking at each chapter.  This at least flags it in the TOC.

**Comment by JimmXinu** [comment] 2020-07-21 15:54
This is caused by an HTML error in the text entered by the author that breaks the HTML parsing.  There's an `<a href=...>` tag that lacks a closing `"` on the `href`:

![Capture](https://user-images.githubusercontent.com/11446969/88076585-dda24980-cb3f-11ea-9e70-f5567709b854.PNG)

So this is a problem with that chapter, not something FFF can fix.

**Closed by JimmXinu** 2020-07-21 15:54 UTC

**Comment by JimmXinu** [comment] 2020-07-27 16:02
[This post](https://www.mobileread.com/forums/showthread.php?p=4015778&postcount=4359) appears to be another case of the same thing.

However, the chapter reported in this issue isn't there anymore.
