### ISSUE TITLE
Issues in Spacebattles and Sufficent Velocity

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#199] opened 2017-07-01 17:51 UTC
In the following stories FanficFare downloads only one post for some reason while the story has threadmarks:
https://forums.sufficientvelocity.com/threads/just-trying-to-survive-here-si-multicross.31422/
https://forums.spacebattles.com/threads/just-trying-to-survive-here-si-multicross.397871/
https://forums.sufficientvelocity.com/threads/panopticon-a-game-of-posthumans-perniciousness-paranoia-politics-and-plasmaguns.47/

Other threads work though

**Comment by JimmXinu** [comment] 2017-07-01 22:00
Okay, this is a little odd.

The basic problem as you describe it was caused by sites changes.  That's already fixed in current test version and will be in next release.

BUT!  All three of those stories have  utf8 characters in their threadmarks that are causing an encoding error for me in CLI on Win10.  I will need to investigate that more, but it may be a few days before I have time.

So there is a problem, I'm just not sure it's the one you reported. :-)

**Comment by JimmXinu** [comment] 2017-07-02 03:48
Okay, I've figured out a fix(1da7f6ec159bee18b650fa074d2d59d4721e3653).  New test version out hopefully tomorrow.

**Comment by JimmXinu** [comment] 2017-07-03 16:27
Test version is out.  Will be in next release.

**Closed by JimmXinu** 2017-07-03 16:27 UTC
