### ISSUE TITLE
Fanfiction.net stories give a HTTP error each time

### ISSUE THREAD

**Issue by pololoduck** [JimmXinu/FanFicFare#1047] opened 2024-03-16 16:26 UTC
Hello, I was trying to use fanfic fare with fanfiction.net stories but every story URL I add gives me this error in the log: 

HTTP Error in FFF '403 client error: Forbidden for url: 

I don't know what to do and would really appreciate any help.

**Comment by JimmXinu** [comment] 2024-03-16 16:38
Duplicate of #1036

**Closed by JimmXinu** 2024-03-16 16:38 UTC
