### ISSUE TITLE
Cloudflare and FanFiction.net doing its thing again

### ISSUE THREAD

**Issue by chocolatechipcats** [JimmXinu/FanFicFare#703] opened 2021-06-01 21:42 UTC
FanFicFare 4.3.0, Calibre running from source. 

Attempting to update from FFNet gives out a Cloudflare 2 error. Several other users have reported this on MobileRead. Cache works as expected. Checked Twitter and there's no indication that FictionPress is working on an update, but I will keep monitoring. 

Not much to be done about it (there doesn't seem to be any recent updates to the scraper), but at least here's a report to monitor the issue.

**Comment by Twilight666** [comment] 2021-06-02 14:48
I don't know if it is the same thing but I get the following error:

> cloudscraper.exceptions.CloudflareCaptchaProvider: Cloudflare Captcha detected, unfortunately you haven't loaded an anti Captcha provider correctly via the 'captcha' parameter.
> 
> During handling of the above exception, another exception occurred:
> 
> fanficfare.exceptions.FailedToDownload: cloudscraper reports: "Cloudflare Captcha detected, unfortunately you haven't loaded an anti Captcha provider correctly via the 'captcha' parameter."

It looks like there is a change in cloudscraper's use and it needs a new option to be set.
Or maybe it's an old option and now it raises an error... I don't know

**Comment by JimmXinu** [comment] 2021-06-02 14:56
It looks like ffnet has increased their Cloudflare blocking level again.

As far as I know, there isn't anything more we can do in FFF than there was the last time this happened.

I suggest reviewing these resources:

FAQ:
https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-am-i-having-errors-downloading-from-fanfictionnet--why-am-i-getting-cloudflare-errors-downloading-from-fanfictionnet

Browser Cache Feature:
https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature

Browser Proxy (third party):
https://github.com/nsapa/fanfictionnet_ff_proxy

**Comment by NightMachinary** [comment] 2021-06-02 15:01
@JimmXinu We can use `puppeteer` though? I just tested my https://github.com/NightMachinary/.shells/blob/master/scripts/javascript/curlfull.js , and it worked fine. Using the browser cache is not a very good solution (I use `fanficfare` on a server).

**Comment by NightMachinary** [comment] 2021-06-02 15:03
@JimmXinu A general workaround is to let the user supply a downloader, like `youtube-dl`'s `--external-downloader`, if you don't like bundling `puppeteer`.

**Comment by JimmXinu** [comment] 2021-06-02 15:27
First off, I'm not doing anything about this in a hurry.  More than once, we've seen ffnet's CF level go up for a while and then go back down after a while--think days, not hours.

Second, Cloudflare is a service specifically for detecting and blocking automated access.  I assume (and past evidence agrees) that they can already block well known automated browser tools.  If I recall correctly, earlier in the year, we experimented with headless proxy browsers and all of them were blocked after a few requests.

That's why our current generation of work arounds are based on using a live browser.

**Comment by Twilight666** [comment] 2021-06-02 15:27
I was already using Cache... but since I reread the wiki I tried and I downloaded the entire story using WebToEpub and it downloaded the whole story.
But when I immediately afterwards used FFF is still not working

**Comment by chocolatechipcats** [comment] 2021-06-02 15:35
> I was already using Cache... but since I reread the wiki I tried and I downloaded the entire story using WebToEpub and it downloaded the whole story.
> But when I immediately afterwards used FFF is didn't work

Try `use_browser_cache_only:true` to prevent it falling back to the site. I'm assuming it's some user error, but for whatever reason I have trouble getting it to use the cache if it's unset.

**Comment by timgblack** [comment] 2021-06-02 23:21
Is it worth - if ffn keep this up - investigating how their app bypasses these checks?

**Comment by mcepl** [comment] 2021-06-03 12:10
> Try `use_browser_cache_only:true` to prevent it falling back to the site. I'm assuming it's some user error on my end, but for whatever reason I have trouble getting it to use the cache if I only set `use_browser_cache:true.`

This is what I've tried (using FanFicFare 4.3.0 and Firefox 88):

1. Download https://www.fanfiction.net/s/13747780/1/ with WebToEpub
2. Add `browser_cache_path:/home/matej/.cache/mozilla/firefox/uxi2c7cz.default/cache2` to `[defaults]` in `personal.ini`
3. Run:
```sh
tmp@stitny$ fanficfare -o use_browser_cache_only=true https://www.fanfiction.net/s/13747780/1/
cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.

During handling of the above exception, another exception occurred:

fanficfare.exceptions.FailedToDownload: cloudscraper reports: "Detected a Cloudflare version 2 Captcha challenge, This feature is not available...."
```
Something’s wrong. Why even with `use_browser_cache_only=true` I get Internet connection?

**Comment by JimmXinu** [comment] 2021-06-03 16:29
Do you also have `use_browser_cache:true` under `[www.fanfiction.net]`?  `use_browser_cache_only:true` doesn't do anything without `use_browser_cache:true`

**Comment by mcepl** [comment] 2021-06-03 23:39
> Do you also have `use_browser_cache:true` under `[www.fanfiction.net]`? `use_browser_cache_only:true` doesn't do anything without `use_browser_cache:true`

Which is a bit weird, isn't it? Anyway, this works.
```sh
fanficfare -o use_browser_cache=true -o use_browser_cache_only=true -o use_cloudscraper=false \
    https://www.fanfiction.net/s/13747780/1/
```

**Comment by chocolatechipcats** [comment] 2021-06-07 10:17
> I'm assuming it's some user error on my end, but for whatever reason I have trouble getting it to use the cache if I only set `use_browser_cache:true.`

Just for posterity, `check_next_chapter:true` seemed to be the cause of this.

**Comment by eltonfreak** [comment] 2021-06-09 14:54
I have also recieved the following errors in the last 24 hours.

Status
Title
Author
Comment
URL
Error
Unknown
Unknown
cloudscraper reports: "Detected a Cloudflare version 2 Captcha challenge, This feature is not available...."
https://www.fanfiction.net/s/5598642/1/
Error
Unknown
Unknown
cloudscraper reports: "Detected a Cloudflare version 2 Captcha challenge, This feature is not available...."
https://www.fanfiction.net/s/5244813/1/
Error
Unknown
Unknown
cloudscraper reports: "Detected a Cloudflare version 2 Captcha challenge, This feature is not available...."
https://www.fanfiction.net/s/5012016/1/Partners

**Comment by mcepl** [comment] 2021-06-09 15:11
> I have also recieved the following errors in the last 24 hours.

Yes, Cloudflare is acting again, and there is nothing we can do about it. Workaround with WebToEpub is the only thing I know to work.

**Comment by erd00073** [comment] 2021-06-14 20:19
> Is it worth - if ffn keep this up - investigating how their app bypasses these checks?

The author of at least one other 3rd party reader app I know of has already looked at it and states that the code at issue is a  totally obfuscated mess that he has no intention of trying to dig into.  If you want to try, feel free.  But, keep in mind, even if you manage to figure something out, as soon as more than a few people try to use it they'll just update the app and invalidate everything you did.  

The owner of FFN is focused on getting his ad revenue, and going to war with a company like Cloudflare is a zero sum fight you aren't going to win in the end.  The only thing you can try to do is work around them like Jimm is with the FFF browser cache feature.  I just hope FFN doesn't try to implement some form of cache busting technique.

**Comment by Edocsil** [comment] 2021-06-14 20:25
> > Is it worth - if ffn keep this up - investigating how their app bypasses these checks?
> 
> The author of at least one other 3rd party reader app I know of has already looked at it and states that the code at issue is a totally obfuscated mess that he has no intention of trying to dig into. If you want to try, feel free. But, keep in mind, even if you manage to figure something out, as soon as more than a few people try to use it they'll just update the app and invalidate everything you did.
> 
> The owner of FFN is focused on getting his ad revenue, and going to war with a company like Cloudflare is a zero sum fight you aren't going to win in the end. The only thing you can try to do is work around them like Jimm is with the FFF browser cache feature. I just hope FFN doesn't try to implement some form of cache busting technique.

The official FFN app doesn't have ads, so whatever reason they have for this can't be ad revenue.

**Comment by JimmXinu** [comment] 2021-06-14 20:46
Rather than believing that ffnet has deliberately set out to ruin our collective day, I suspect that they are using Cloudflare for protection from aggressive, automated systems attacking their site.

Unfortunately, individual users with automated download software (IE, us) are extremely similar in appearance from their POV.

I'll add what [I said over on MR](https://www.mobileread.com/forums/showthread.php?p=4130194#post4130194) recently:

> I have lost basically all interest in fighting with ffnet about this. Browser cache works well enough for me for the few active authors I still read on ffnet.
> 
> Unless someone comes up with a radical new idea, I'm not thinking about it anymore right now.
> 
> Many thanks to the members here are willing and able to help each other.

**Comment by mcepl** [comment] 2021-06-14 21:10
> > I have lost basically all interest in fighting with ffnet about this. Browser cache works well enough for me for the few active authors I still read on ffnet.

I basically agree with what you said, with one exception (and no I have no idea how to do it): at least checking that the work has new update. I have still 776 FFN stories (yes, trying to move to AO3 as much as possible, but this is the best I have managed so far) and I have no clue how to check that I am not missing on new chapters. Update itself is done easily with browser cache.

**Comment by chocolatechipcats** [comment] 2021-06-14 21:13
If you have an ffnet account, you can go to Account Page > Alerts > Story Alerts and compare the dates of followed stories to your local copies. Setting up Calibre with a last-updated column will help too.

**Comment by quihi** [comment] 2021-06-14 22:22
I have a discord bot which has been able to access FFN most of the time recently.  Is fanficfare using the latest version of cloudscraper?

**Comment by chocolatechipcats** [comment] 2021-06-14 22:25
Cloudscraper's last update was on April 9, and I believe it's already been incorporated into FFF. Also, the error specifically mentions the version 2 CAPTCHA, which the Cloudscraper developer has behind a paywall (this was discussed in the last thread).

**Comment by MrTyton** [comment] 2021-06-20 21:07
Has anyone even gotten the paywall-d version to work? At this point I'd be willing to shell out a few bucks, but not if it doesn't work with Fanficfare.

**Comment by mcepl** [comment] 2021-06-20 21:09
> Has anyone even gotten the paywall-d version to work? At this point I'd be willing to shell out a few bucks, but not if it doesn't work with Fanficfare.

I haven’t found a paid version. Is there a one?

**Comment by chocolatechipcats** [comment] 2021-06-20 21:12
It was discussed in the last thread:
https://github.com/JimmXinu/FanFicFare/issues/622#issuecomment-756479078

**Comment by kov9413tam** [comment] 2021-07-01 18:58
The Google Chrome extension: WebToEpub still can download from FF.net. 

https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode

**Comment by mcepl** [comment] 2021-07-01 19:00
> The Google Chrome extension: WebToEpub still can download from FF.net.

Works in Firefox as well. But the problem is that some more sophisticated things FFF can do, this extension cannot (namely, ``--update-epub``).

**Comment by arisboch** [comment] 2021-07-01 20:38
@mcepl Better than nothing, especially if one can't use that Windows program to download stuff from FFN, but has a Firefox, Chrome or Chrome-based browser.

**Comment by timgblack** [comment] 2021-07-22 03:28
I run FanFicFare on a headless Raspberry Pi and submit URLs from my phone, so using any cache isn't viable unfortunately. For now, I've just stopped it checking for updates and I'm seriously considering whether it's worth decompiling the app and seeing if the same method it uses is viable (or if using the app cache is viable)...

**Comment by CodeyAce95** [comment] 2021-07-31 20:07
does any one know if there is a fanfiction.net app that let us read like a book instead of scrooling if so please let me know so ican read my books intill this problem is solved beacse the scrolling on fanfiction.net makes me sick

**Comment by chocolatechipcats** [comment] 2021-07-31 20:09
FanFiction.net has an official app. From what I understand all other ones are blocked.

**Comment by CodeyAce95** [comment] 2021-07-31 20:12
[s there a there away around it

**Comment by Edocsil** [comment] 2021-07-31 20:12
> does any one know if there is a fanfiction.net app that let us read like a book instead of scrooling if so please let me know so ican read my books intill this problem is solved beacse the scrolling on fanfiction.net makes me sick

In the official app you can "turn page" with the volume keys, it's an option in the settings.

Not the best place to ask this though..

**Comment by CodeyAce95** [comment] 2021-07-31 20:13
where would i ask i am new here

**Comment by JimmXinu** [comment] 2021-07-31 20:40
Google for fanfiction.net app.  This is off-topic for both this project and this issue.

**Comment by Xyverz** [comment] 2021-08-01 01:34
> It looks like ffnet has increased their Cloudflare blocking level again.
> 
> As far as I know, there isn't anything more we can do in FFF than there was the last time this happened.
> 
> I suggest reviewing these resources:
> 
> FAQ:
> https://github.com/JimmXinu/FanFicFare/wiki/FAQs#why-am-i-having-errors-downloading-from-fanfictionnet--why-am-i-getting-cloudflare-errors-downloading-from-fanfictionnet
> 
> Browser Cache Feature:
> https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature
> 
> Browser Proxy (third party):
> https://github.com/nsapa/fanfictionnet_ff_proxy

Hey @JimmXinu, I've read your BrowserCacheFeature page several times and nowhere in that does it say where this `personal.ini` file I'm supposed to edit is located. I'm getting more and more frustrated the more I try to implement this solution. Can you please update the wiki page or at least inform me where this file is located?

Thanks in advance!

**Comment by JimmXinu** [comment] 2021-08-01 01:40
There's a separate wiki page about INI and the first thing in it is [INI File Location](https://github.com/JimmXinu/FanFicFare/wiki/INI-File#ini-file-location).  

But I will add a link from the BrowserCacheFeature page.

**Comment by Xyverz** [comment] 2021-08-01 01:42
> There's a separate wiki page about INI and the first thing in it is [INI File Location](https://github.com/JimmXinu/FanFicFare/wiki/INI-File#ini-file-location).
> 
> But I will add a link from the BrowserCacheFeature page.

Thank you sir! Much appreciated!

**Comment by erd00073** [comment] 2021-08-01 02:29
> > There's a separate wiki page about INI and the first thing in it is [INI File Location](https://github.com/JimmXinu/FanFicFare/wiki/INI-File#ini-file-location).
> > But I will add a link from the BrowserCacheFeature page.
> 
> Thank you sir! Much appreciated!


Click the down arrow by the FFF button in Calibre, and select the option to configure FFF.  On the configuration page that pops up, click the Personal.ini tab.    There is an "Edit Personal.ini" button there, and once it is open for editing there is a save button at the bottom of the edit window.

One piece of advice I learned the hard way - be very careful using when using copy/paste into Personal.ini.  Somehow (as near as I can tell, anyway) I managed to paste some type of invisible embedded character in there.  It caused me all sorts of random misery with FFF for weeks before ownedbycats on the Mobileread site pointed out to me how to reset Personal.ini to defaults.

**Comment by CodeyAce95** [comment] 2021-09-12 00:02
has any one figured how to get around this i do not care about downloading but i want to update my stories any help would be welcome thank you and god bless

**Comment by JimmXinu** [comment] 2021-09-12 00:17
The only new information is that the [Browser Cache work around](https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature) can also use the cache created by [FanFictionDownloader](https://www.fanfictiondownloader.net/).

**Comment by LoisGNS** [comment] 2021-09-12 02:54
That's terrific news, since it should allow more batching - I think FFD will download whatever I feed it if I give it a list in a file, but can just delete those and re-feed the list into FFF. Which version of FFF do I need to enable the FFD cache? I'm currently using 4.3.0. 

So what I would  do is have use FFF to create the list (read it from a web page or drag/drop the desired items from the page onto its download list), save the resulting list to a .txt file, which I then feed to FFD; let it do its thing to populate the cache, then run the FFF download-from-url action, and finally delete the redundant FFD files. Make sense?

**Comment by CodeyAce95** [comment] 2021-09-12 04:36
would any one have direct instructions for a total noob with pictures if possible i am autistic

**Comment by LoisGNS** [comment] 2021-09-12 05:56
@CodeyAce95, are you looking for instructions regarding using FFD with FFF, along the lines I described above, just specific parts of the process, or something else? For example, do you need help with finding and setting up FFD (looks like you already have and use FFF), or just the bits I described that suggest what might work by using them together? There is a download link to FFD in JimmXinu's post above if you don't already have it.

I haven't yet tried what I described, but once I do (and confirm it works), I could probably put together a Word document with screen-grabs, if that would be helpful - and if this site will let me attach the doc to a message here.  It seems like it allows attachments, I just don't what restrictions, if any, there might be to the types or sizes of the attachments. It may take me a few days to get to it, since I'm behind on some stuff at the moment :)

**Comment by Edocsil** [comment] 2021-09-12 11:26
Alternatively, you can download ffnet fics using a different tool, like [ff2ebook](https://ff2ebook.tk/) or [fichub](https://fichub.net/), personally I'm currently using [FicHub-cli](github.com/FicHub/fichub-cli) and it works fine.

This tools get around cloudfare using [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr), but I don't know if this would work with FFF. In the past ff2ebook just used cookies and it worked too, so that's something that someone could try.

**Comment by CodeyAce95** [comment] 2021-09-12 13:30
> @CodeyAce95, are you looking for instructions regarding using FFD with FFF, along the lines I described above, just specific parts of the process, or something else? For example, do you need help with finding and setting up FFD (looks like you already have and use FFF), or just the bits I described that suggest what might work by using them together? There is a download link to FFD in JimmXinu's post above if you don't already have it.
> 
> I haven't yet tried what I described, but once I do (and confirm it works), I could probably put together a Word document with screen-grabs, if that would be helpful - and if this site will let me attach the doc to a message here. It seems like it allows attachments, I just don't what restrictions, if any, there might be to the types or sizes of the attachments. It may take me a few days to get to it, since I'm behind on some stuff at the moment :)

yes i think that might be just what i need thank you and god bless

**Comment by JimmXinu** [comment] 2021-09-12 15:37
We've discussed **FlareSolverr** [before](https://github.com/JimmXinu/FanFicFare/issues/622#issuecomment-756934042).  It starts a proxy process that starts a puppeteer headless browser process.  [nsapa's Browser Proxy](https://github.com/nsapa/fanfictionnet_ff_proxy) is effectively similar and already working.

However, since FlareSolverr offers binary downloads (for win and linux), I may attempt using it.  But I would [point out the following](https://github.com/FlareSolverr/FlareSolverr#captcha-solvers) from FlareSolverr's home page about captcha solvers:
> ⚠️ At this time none of the captcha solvers work. You can check the status in the open issues. Any help is welcome.
___
The **fichub** projects listed are frontends to an AJAX API server.  I don't see a public repository for the actual download code.  By running all downloads through their own server, all issues with running headless browsers are at least concentrated in one place.

FFF [used to have a web version](https://github.com/JimmXinu/FanFicFare/wiki#web-service-version) which operated under somewhat similar basic architecture, but it's been retired:
> I continued to support the web service in recent years as a legacy for the users who can't run the CLI or Calibre versions. But I'm not interested in spending my money on it, or dealing with the accounting and possible tax implications of collecting donations to run it.
___
@LoisGNS - If you are willing to put together words and pictures for a user guide on using FFDL and FFF together, I would be willing to convert it to markdown and add it to the project as a wiki page--properly credited, of course.

**Comment by LoisGNS** [comment] 2021-09-13 02:23
I started such a document, doing screen-grabs as I went. **But** it didn't work. I am using ver 4.5.0 of FFF and 0.9.2 of FFD. Do I need a different version of one or both?

**Comment by JimmXinu** [comment] 2021-09-13 02:28
You probably need the latest FanFictionDownloader, v0.9.4.

**Comment by chocolatechipcats** [comment] 2021-09-13 03:10
I can confirm it works with 0.9.4. 

Check that you're using the right cache folder. There's `\cache\` but you actually want `\cache\QtWebEngine\Default\Cache`. I made this mistake. Mine has several data_# files and an index.

**Comment by LoisGNS** [comment] 2021-09-13 03:51
I just tried after updating FFD to 0.9.4, and it still isn't working for me. 

@chocolatechipcats, are you saying I need to change the browser_cache_path in personal.ini from the one I use when just clicking through in FireFox? That one is  C:\Users\[myusername]\AppData\Local\Mozilla\Firefox\Profiles\[myfolder].default\cache2, which has two subfolders: "doomed" and "entries" and a file called "Index" with no extension. There's lots of stuff under Entries. This works with the browser-cache method, and is the one that was described in the instructions for it.

I don't find any folder like the one you describe. I looked in c:\users (etc.), as well as the FFD and Calibre folders. I also asked Windows to search for it, and it didn't find it either.

There is also a Chrome browser cache shown as an option in the instructions, browser_cache_path:C:\Users\YourUser\AppData\Local\Google\Chrome\User Data\Default\Cache or trying another profile name in place of "default". I don't have a Chrome profile name other than "default," so tried that, which didn't work either. 

I'm stumped now.

**Comment by JimmXinu** [comment] 2021-09-13 04:12
Yes, you must change `browser_cache_path`.  

FFDL uses it's own browser instance, not your usual browser. As I [documented](https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature#fanfictiondownloader), for me the FFDL cache dir was `C:\Users\YourUser\AppData\Local\fanficdownloader\cache\QtWebEngine\Default\Cache`

**Comment by LoisGNS** [comment] 2021-09-13 06:48
Ok, that worked. I hadn't seen the additional documentation. I attached illustrated documentation of the process. Feel free to process as appropriate and add to the wiki.

[Batch downloading with FFF and FFD.docx](https://github.com/JimmXinu/FanFicFare/files/7151897/Batch.downloading.with.FFF.and.FFD.docx)

**Comment by JimmXinu** [comment] 2021-09-13 16:55
Thanks!  I've created a new wiki page: [FanFictionDownloader-FanFicFare-Batch](https://github.com/JimmXinu/FanFicFare/wiki/FanFictionDownloader-FanFicFare-Batch)

**Comment by CodeyAce95** [comment] 2021-09-13 17:52
i can;t find cache in my personal.ini am i do somthing wrong

**Comment by mcepl** [comment] 2021-09-13 19:14
> i can;t find cache in my personal.ini am i do somthing wrong

Something like this line in `[defaults]` section `~/.fanficfare/personal.ini` should help:
```
browser_cache_path:/home/matej/.cache/mozilla/firefox/uxi2c7cz.default/cache2 
```

**Comment by JimmXinu** [comment] 2021-09-16 18:56
I've posted test versions with an experiment feature to support using [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr).

**If you are not able to obtain, install and run FlareSolverr on your own from the FlareSolverr documentation, I politely suggest that you are not a good candidate for evaluating this experimental feature at this time.**

After you have FlareSolverr running, to enable it in FFF use:
```
[www.fanfiction.net]
use_flaresolverr_proxy:true
# optional settings with default values shown:
#flaresolverr_proxy_address:localhost
#flaresolverr_proxy_port:8191
```

Obviously, this is mostly for ffnet, but it does appear to work for many other sites.  Notably, it does *not* work for SpaceBattles, SufficientVelocity, QQ and I assume the other XenForoForum sites.  FlareSolverr fails with a 'Page Crashed' error.

I've tested the FFF code in Win10, Mac and Ubuntu 21.04 using Calibre 5.x official releases and Win10 CLI.  I've only run FlareSolverr on Windows and used the `flaresolverr_proxy_address` setting to point the different Calibre to the same FlareSolverr proxy server.

**Comment by Edocsil** [comment] 2021-09-17 18:17
Sadly if there is a way to make this work on android, I don't know it. It does work fine on a desktop, even if I can't find a reasonable excuse to keep the desktop on just so my phone can update all its stories with a single command.

**Comment by JimmXinu** [comment] 2021-09-22 17:13
FYI, I believe the flaresolverr proxy solution is solid enough to try for anyone who's comfortable downloading and running [flaresolverr](https://github.com/FlareSolverr/FlareSolverr).

Be warned, however, that I don't intend to offer support for flaresolverr itself.

**Comment by mcepl** [comment] 2021-09-22 17:24
Is there some comparison between advantages and disadvantages of flaresolverr and FanFictionDownloader? Are they essentially the same or is there some difference?

**Comment by chocolatechipcats** [comment] 2021-09-22 17:24
> Is there some comparison between advantages and disadvantages of flaresolverr and FanFictionDownloader? Are they essentially the same or is there some difference?

Something that came up on the MR thread is that FFDL's cache doesn't get the cover image, if that's important to you.

**Comment by mcepl** [comment] 2021-09-22 17:27
> Something that came up on the MR thread is that FFDL's cache doesn't get the cover image, if that's important to you.

OK, but if I use FFDL via `use_nsapa_proxy:true` then there is no difference?

**Comment by Edocsil** [comment] 2021-09-22 17:45
> Is there some comparison between advantages and disadvantages of flaresolverr and FanFictionDownloader? Are they essentially the same or is there some difference?

I don't know how FFDL's solution work, but with FS you just set it up once and forget, after that FFF will just download any fics without you having to do anything, as if this whole issue didn't exist.

I've been downloading a couple dozen ffnet fics everyday since I setup FS and I've yet to have any issue with cloudfare.

**Comment by JimmXinu** [comment] 2021-09-22 17:52
`use_nsapa_proxy:true` and `use_flaresolverr_proxy:true` are roughly equivalent.  `use_browser_cache:true` works differently.

 In the first case, you need to have downloaded and started [fanfictionnet_ff_proxy](https://github.com/nsapa/fanfictionnet_ff_proxy) and in the second case you need to have downloaded and started [flaresolverr](https://github.com/FlareSolverr/FlareSolverr).   For both, FFF talks to a proxy server which is running a full fledged (albeit headless) browser instance to do the actual page requests and deal with Cloudflare.

The [browser cache feature](https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature) is different, it looks for pages that have already been downloaded in a supported browser cache.  

Using [FFDL](https://www.fanfictiondownloader.net/) with `use_browser_cache:true` is equivalent to using a normal browser and manually viewing the pages (or using [WebToEpub](https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature#WebToEpub)).

**Comment by chocolatechipcats** [comment] 2021-09-22 17:58
I tested Flaresolverr and it worked perfectly. :) Does Calibre allow for launching of external applications? If so, it would be nice to input the executable path and have FFF automatically launch that.

**Comment by JimmXinu** [comment] 2021-09-22 18:14
> Does Calibre allow for launching of external applications? If so, it would be nice to input the executable path and have FFF automatically launch that.

You see that right there?  That's why I dragged my feet on supporting this type of proxy.  

I have no interest in trying to figure out how to launch a proxy from inside Calibre.  And even less interest in supporting it across all the different py2/py3/mac/linux/win combinations.  And the inevitable firewall/antivirus/antimalware issues.  

Plus there's the fact that at any moment ffnet could ratchet up requiring captchas, negating all progress gained.

**Comment by LoisGNS** [comment] 2021-09-23 03:37
So after installing and running flaresolverr, what then? Do I make changes in my fff config to use it? When I run it, it executes in a DOS windo w and then, I guess, just sits there waiting? Would the correct approach in fff be to turn off use-cache so that flaresolver could do its thing?

**Comment by LoisGNS** [comment] 2021-09-23 06:47
@chocolatechipcats How did you test? I haven't had any success with it. I did the following:
Downloaded and extracted Flaresolverr to a folder named Flaresolverr.
Ran the executable, which popped up a window (also tried running it from the command line, and it reported 
INFO Listening on http://0.0.0.0:8191
Edited FFF's Personal.ini (using fff 4.50 in case that matters) to comment out use_browser_cache and replace it with use_flaresolverr_proxy:true
Note: the "use_flaresolverr_proxy" portion of that turns red, which suggests it's unrecognized
Tried to update a fic, and got the usual errormessage regarding Cloudflare.
At this point I reversed the changes to personal.ini and used the FFD cache successfully.

What am I missing about Flaresolverr?

**Comment by LoisGNS** [comment] 2021-09-23 09:29
Where can I get 4.5.10 of the plugin? After various attempts at testing, I conclude that's what I probably need, but all I can find is some files on the Code page, which don't seem to be the right collection of files for the plugin. The more ususal sources only go up to 4.5.0,

**Comment by Twilight666** [comment] 2021-09-23 09:44
Go here:
https://www.mobileread.com/forums/showthread.php?t=259221

The second post has the latest test version (anything that doesn't end in .0)

**Comment by LoisGNS** [comment] 2021-09-23 10:03
Aha! I was on that page, but didn't scroll down  to the second post - doh!

**Comment by LoisGNS** [comment] 2021-09-24 01:34
Funny thing is, I found the MobileRead page and just didn't scroll down far enough to find the link to the test version. Having as many places as possible to find the 'usual places' is definitely helpful.

**Comment by Brendan-McDonnell** [comment] 2021-10-14 05:05
> The **fichub** projects listed are frontends to an AJAX API server. I don't see a public repository for the actual download code. By running all downloads through their own server, all issues with running headless browsers are at least concentrated in one place.

Looks like fichub is a front end for [`hermes`](https://github.com/FanFicDev/hermes), which is a convoluted mess with nested hard-coded if statements for specific fandoms on different sites. The actual scraping on it just... [goes through the normal `requests` library](https://github.com/FanFicDev/hermes/blob/8acf8f06eade66565eb2f9f81581ad47ef7a5ff9/skitter_client.py#L53-L84). As best I can tell, here's the code that does all the requests for every single site they manage:
```python
r = requests.get(
        apiUrl,
	self.headers,
	params,
	self.extraData,
	self.auth,
	self.timeout
)
```
And yet, it's working? I just checked with a work on fanfiction.net that was published a week ago or so.

It looks like the request parameters are filled by a bunch of configuration variables. They do mention that these are _required_ to be filled for FFN to work. **So they somehow have a working FFN scraper via setting a `baseUrl`, `apiKey`, `uname`, and/or `upass` and just using `requests`.**

I'm not sure what's going on here. Did they somehow get access to the [API beta FFN mentioned on twitter in January and never since](https://twitter.com/FictionPress/status/1347730173181915138?s=20)?

**Comment by Brendan-McDonnell** [comment] 2021-10-17 19:31
> 
> 
> Hermes isn't worth the effort it takes to install it, tbh (it's a pain to install and configure that postgresql stuff it needs).

I don't know, it doesn't look so bad. Wouldn't be a difficult Dockerfile + Docker Compose setup. Would be nice if it had one provided though

**Comment by MrTyton** [comment] 2021-11-08 02:10
Even after the version of 4.7 release, I think that Flaresolverr v2 still doesn't work

```
2021-11-08T02:08:16+00:00 INFO REQ-188 Cloudflare detected

2021-11-08T02:08:18+00:00 INFO REQ-188 Challenge solved

2021-11-08T02:08:18+00:00 INFO REQ-188 Response in 5.024 s

2021-11-08T02:08:30+00:00 INFO REQ-189 Incoming request => POST /v1 body: {"cmd":"request.get","url":"https://www.fanfiction.net/s/13789183/45/The-Self-Made-Man","maxTimeout":30000,"download":true,"cookies":[{"name":"__cf_bm","value":"soXtaXigV8Go1GAbIVqGLurvyoWjNEpFLc6uFwjG0VA-1636337295-0-AW9hG5VIeLm8cTWv4yCzTTr14IMFXSgs4FYK5lrAEC1dE/7J3wTjQ9rbUlXtcSosDlLy8vqD7CJIsPy4V3p+TN4=","domain":".fanfiction.net","path":"/","expires":1636339095},{"name":"cf_clearance","value":"pu0iL7beRJU.QxZMKuvuW5QkmwrNexR5exqHWTBVoMg-1636337297-0-150","domain":".fanfiction.net","path":"/","expires":1667876897},{"name":"cf_chl_2","value":"3194f4f2b4fd7a8","domain":"www.fanfiction.net","path":"/","expires":1636340896},{"name":"cf_chl_prog","value":"x9","domain":"www.fanfiction.net","path":"/","expires":1636340898}],"postData":null}

2021-11-08T02:08:30+00:00 WARN REQ-189 Request parameter 'download' was removed in FlareSolverr v2.
```

from the Flaresolverr output, so it seems like the v2 code isn't triggering.

**Comment by chocolatechipcats** [comment] 2021-11-08 02:14
At about 21:15 GMT on November 7 (if I did the timezone calculations correctly), I was able to succesfully update a ffnet fic with flaresolverr. I got similar log output to you.

**Comment by MrTyton** [comment] 2021-11-08 02:15
> At about 21:15 GMT on November 7 (if I did the timezone calculations correctly), I was able to succesfully update a ffnet fic with flaresolverr. I got similar log output to you.

I'm trying it live right now, with Flaresolverr 2.0.0 and FFF 4.7.0, and that's still what I'm getting. Trying Flaresolverr 1.2.9 kept timing out.

**Comment by chocolatechipcats** [comment] 2021-11-08 02:17
Are you using Calibre? A few days ago, I seem to recall having a Flaresolverr download seem to stall up on me - the Calibre progress dialog was at something like 96% close to an hour. I eventually cancelled it and used FFDL for that one fic, but haven't had the issue recur again.

**Comment by MrTyton** [comment] 2021-11-08 02:25
Using the CLI. When it times out, it's on the first request with 1.2.9, and the request for v2 is incorrectly formatted.

**Comment by MrTyton** [comment] 2021-11-08 03:10
Ah, this was my error, sorry for the spam. It seems as though it is working, albeit slowly, but that the download param is always added - FlareSolverr just ignores the param, but still throws the warning.

**Comment by JimmXinu** [comment] 2021-11-08 03:25
Correct.  Since Flaresolverr warns, but continues to work, I've left the `download` flag in for 1.2.9 and in the hope future versions will honor it again.

**Comment by mcepl** [comment] 2021-11-08 09:03
And just for those who think too slowly like myself. Just browsing through the story in the browser (to fill the cache) and using
```sh
fanficfare -o use_browser_cache=true -o use_browser_cache_only=true URL
```
still works (make an alias for it). Only you have to use full URL (e.g., ``https://www.fanfiction.net/s/13979293/1/Revelations-Regarding-Instructional-Services``, not just ``https://www.fanfiction.net/s/13979293``).

**Comment by mcepl** [comment] 2021-11-08 09:04
And just for those who think too slowly like myself. Just browsing through the story in the browser (to fill the cache) and using
```sh
fanficfare -o use_browser_cache=true -o use_browser_cache_only=true URL
```
still works (make an alias for it). Only you have to use full URL (e.g., ``https://www.fanfiction.net/s/13979293/1/Revelations-Regarding-Instructional-Services``, not just ``https://www.fanfiction.net/s/13979293``).

**Comment by MrTyton** [comment] 2022-09-12 01:37
Would it be possible to update [this](https://github.com/JimmXinu/FanFicFare/blob/951cc73e46ec8763c8e9e944074745a0b0a4e649/fanficfare/flaresolverr_proxy.py#L71) line to either have a 60sec timeout or to have it be a config option? Flaresolverr recently had an [update](https://github.com/FlareSolverr/FlareSolverr/commit/0e2452e40e8f1a4e0b46d70bc7fbcec15b27004d) which adds a 30sec delay as a temp fix to get around a CloudFlare update, but since FFF uses a hard limit of 30sec it will always time out.

**Comment by JimmXinu** [comment] 2022-09-12 02:00
Sure, why not.

**Comment by beebutler** [comment] 2022-10-06 00:06
I am struggling as I have never struggled before in my life. No matter what I do I cannot get the ini to save correctly. If I only change "YourUser" to my user "beebutler" I get 'line outside section' error. If I put the full address I get from "about:cache" I get 'line outside section' again. What am I missing? Also I commented out "browser_cache_age_limit:4.0" cause that errors also. Please help me.

**Comment by JimmXinu** [comment] 2022-10-06 02:40
That error suggests that you haven't included appropriate section lines, don't have your settings under that section lines, or have typo'ed the section lines some how.  Without knowing what's in your personal.ini, all I can do is point you to the wiki pages:

https://github.com/JimmXinu/FanFicFare/wiki/BrowserCacheFeature
https://github.com/JimmXinu/FanFicFare/wiki/INI-File

Reviewing what's in the BrowserCacheFeature page, I see that the example ini text doesn't include the `[defaults]` line; it is mentioned in the preceding text.  I'll add it.

**Comment by JimmXinu** [comment] 2022-10-06 02:42
I'm closing this issue now.  The situation, poor as it is, seems to have stabilized.

**Closed by JimmXinu** 2022-10-06 02:42 UTC

**Comment by beebutler** [comment] 2022-10-06 03:04
That did the trick. Thank you for the reply. All good now.
