### ISSUE TITLE
Fanfiction.net: call() got an unexpected keyword argument: log_viewer_unique_name

### ISSUE THREAD

**Issue by Umo022** [JimmXinu/FanFicFare#120] opened 2016-05-21 03:50 UTC
Since updating to the latest FanFicFare (2.3.2), whenever I try to add or update any ebook from Fanfiction.net, I've been getting an error from "call()" complaining about log_viewer_unique_name.

The error is happening by this call when adding:
self.gui.proceed_question(do_update_func,
                                  payload, htmllog,
                                  _('FanFicFare log'), _('FanFicFare download complete'), msg,
                                  show_copy_button=False,
                                  log_viewer_unique_name="FanFicFare log viewer")

or this call when updating:
self.gui.proceed_question(self.update_error_column,
                                 payload, htmllog,
                                 _('FanFicFare log'), _('FanFicFare download ended'), msg,
                                 show_copy_button=False,
                                 log_viewer_unique_name="FanFicFare log viewer")

Since I'm on MacOS 10.6.8 (Snow Leopard), I have to use calibre 1.48, so this might be a consequence of updated python libraries in calibre 2.xx??

----------
ERROR LOG FROM ATTEMPT TO ADD RANDOM FANFIC:

URL: https://www.fanfiction.net/s/11956807/1/The-Remembrall

calibre, version 1.48.0
ERROR: Unhandled exception: <b>TypeError</b>:__call__() got an unexpected keyword argument 'log_viewer_unique_name'

calibre 1.48  isfrozen: True is64bit: True
Darwin-10.8.0-i386-64bit Darwin ('64bit', '')
('Darwin', '10.8.0', 'Darwin Kernel Version 10.8.0: Tue Jun  7 16:33:36 PDT 2011; root:xnu-1504.15.3~1/RELEASE_I386')
Python 2.7.5
OSX: ('10.6.8', ('', '', ''), 'i386')
Traceback (most recent call last):
  File "site-packages/calibre/gui2/__init__.py", line 407, in dispatch
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1717, in download_list_completed
TypeError: __call__() got an unexpected keyword argument 'log_viewer_unique_name'

**Comment by JimmXinu** [comment] 2016-05-21 04:17
I'll look into it tomorrow.  But for now, you can manually install the [previous version](https://github.com/JimmXinu/FanFicFare/releases/tag/v2.3.1) if you like.

**Comment by Umo022** [comment] 2016-05-21 05:37
Thanks, I've done that.

Just for your information, FanFicFare 2.3.1 successfully both adds and updates stories from FanFiction.com with no errors.

**Comment by cryzed** [comment] 2016-05-21 14:45
The issue is that the 2.3.2 release uses a new feature of `calibre.gui2.ProceedQuestion` in the `__call__` method: `log_viewer_unique_name`. This keyword-argument is not available in Calibre API before version 2.5.7 and was [contributed by  JimmXinu recently](https://github.com/kovidgoyal/calibre/commit/463603dab0ac8cf169e1199bb41ad63599cbcb16).

There are two ways around this: Either remove usage of this new feature entirely or make it dependent on the used Calibre version.

**Comment by JimmXinu** [comment] 2016-05-21 15:28
Fixed in 3cc3b3201212168ef5d0384378e7a5deec41463b -- @cryzed got to it before I did--thanks.

There's a new test version of the plugin posted here:

http://www.mobileread.com/forums/showthread.php?p=3084025#post3084025

**Closed by JimmXinu** 2016-05-21 15:28 UTC
