### ISSUE TITLE
AO3 skipped chapter number causes problem when -b after it (was Issue with AO3 on CLI)

### ISSUE THREAD

**Issue by Twilight666** [JimmXinu/FanFicFare#470] opened 2020-02-20 21:15 UTC
I was trying to download

> https://archiveofourown.org/works/17947397[110-]

(This story has chapter 50 missing)
It should have downloaded chapters 110-121, instead it says it downloaded 111-120.

First of all while it says it started downloading from chapter 111 the first chapter is 

> https://archiveofourown.org/works/17947397/chapters/53225965

which is 110 (the correct one)

However the chapter title is the title of chapter 111.
And all other titles are wrong with each chapter having the next chapter's title

Finaly Chapter 121 is not there anyway.

I think the entire mess is because of the missing chapter

**Comment by JimmXinu** [comment] 2020-02-20 22:04
As far as I can tell, FFF is doing everything as intended.

You've already identified the issue: The author skipped 50 when numbering their chapters and therefore all the subsequent chapters are off by one.  (I don't know why you're reporting it an FFF issue when you've already figured it out.)

Further, if you have FFF renumbering chapters, which is common, but not default:
```
add_chapter_numbers:true
strip_chapter_numbers:true
```
...then the problem will basically disappear except for exactly the sort of occasional confusion you're seeing when comparing to the author's off-by-one list.

Look at the [same story on ffnet](https://www.fanfiction.net/s/13220537/120/A-Wand-for-Skitter) and 50 isn't skipped.

**Comment by Twilight666** [comment] 2020-02-20 22:10
No I mean for example that https://archiveofourown.org/works/17947397/chapters/53225965 is downloaded and while it's original name is `110. Choices` in the epub the title is `111. Skrewt-2`
Also since I am using [110-] it should download everything from whatever FFF understands 110 is until the end.
But the last chapter is not downloaded.

Yes this is a mistake in AO3 but it affects the result in FFF if you use the [X-] when a chapter is missing

**Comment by JimmXinu** [comment] 2020-02-20 22:32
When you said the 'chapter' is wrong and the 'chapter is missing', I assumed chapter title and text as a unit and didn't look any farther than the numbers.

What you were trying to get across--and I wasn't getting--is that the chapter ***text*** and the chapter ***title*** are disagreeing--not just the number.  IE, `Skrewt-2` starts with:

> Feeling awkward in my dress I stepped outside the bathroom to let Millicent take a look at me.

When it should be:
> “I think Karkaroff is in trouble.”

And I see what the problem is, but I need to think a little bit about the best way to address it permanently.

In the mean time, you could set `use_view_full_work:false` to avoid the problem.

What's going on is that the `view_full_work` page is *also* missing `chapter-50`--which isn't surprising.  When FFF tries to download chapter 50, it can't find it and turns off `use_view_full_work` for the rest of the download.  But as you found, if you're starting *after* 50, FFF doesn't realize that AO3's chapter numbers are wrong.

**Comment by JimmXinu** [comment] 2020-02-20 23:12
Some further history: #208 is the same issue, fixed in a3ab3e013347d789ec07588562f9f5e032652f5a -- incompletely as it turns out.  

(I had initially blew it off as an obscure one-off error before [this report](https://groups.google.com/forum/#!msg/fanfic-downloader/X7bLajYzKzY/BwII4h7SCAAJ).)

At least this gives me three examples to work with:
- https://archiveofourown.org/works/17947397
- https://archiveofourown.org/works/626020
- https://archiveofourown.org/works/10093553

**Closed** 2020-02-21 00:15 UTC

**Comment by JimmXinu** [comment] 2020-02-21 00:17
Plugin and CLI test versions posted in the usual places.
