### ISSUE TITLE
Royalroad scraping is broken (standalone and calibre plugin)

### ISSUE THREAD

**Issue by greenaar** [JimmXinu/FanFicFare#754] opened 2021-11-02 04:41 UTC
Using https://www.royalroad.com/fiction/46550 as an example (all display this behaviour)

.Failed to read epub for update: (name 'ts' is not defined) Continuing with update=false
.Traceback (most recent call last):
  File "/usr/local/bin/fanficfare", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/fanficfare/cli.py", line 310, in main
    do_download(url,
  File "/usr/local/lib/python3.10/site-packages/fanficfare/cli.py", line 410, in do_download
    adapter.getStoryMetadataOnly()
  File "/usr/local/lib/python3.10/site-packages/fanficfare/adapters/base_adapter.py", line 308, in getStoryMetadataOnly
    self.doExtractChapterUrlsAndMetadata(get_cover=get_cover)
  File "/usr/local/lib/python3.10/site-packages/fanficfare/adapters/base_adapter.py", line 412, in doExtractChapterUrlsAndMetadata
    return self.extractChapterUrlsAndMetadata()
  File "/usr/local/lib/python3.10/site-packages/fanficfare/adapters/adapter_royalroadcom.py", line 161, in extractChapterUrlsAndMetadata
    self.story.setMetadata('dateUpdated', self.make_date(dates[-1]))
  File "/usr/local/lib/python3.10/site-packages/fanficfare/adapters/adapter_royalroadcom.py", line 64, in make_date
    return datetime.fromtimestamp(float(ts))
NameError: name 'ts' is not defined

This started today, and is almost certainly the result of a change on their side.

**Comment by greenaar** [comment] 2021-11-02 04:42
Oh, Latest version (CLI and plugin), latest calibre.

**Comment by Dioxycillin** [comment] 2021-11-02 04:46
Interesting that we both posted about the issue 1 minute apart, I don't have full knowledge but I concur with your assessment that it looks like something on their side, although I am curious what it is, since it doesn't seem like captcha/similar protection so hopefully it is fixable.

**Comment by HazelSh** [comment] 2021-11-02 12:03
Can confirm, reproduced on three other stories so it's widespread, probably site wide, probably a change to the story or chapter pages. I have a math exam in two days, but if it's not fixed by this weekend, I'll dig into the adapter then and see what I can do.

**Comment by Twilight666** [comment] 2021-11-02 13:58
I had the NameError: name 'ts' is not defined but then I went to the latest test version and it was fine.
Is everyone else using the latest test version or the latest release version?

**Comment by JimmXinu** [comment] 2021-11-02 15:11
Dup of #753

**Closed by JimmXinu** 2021-11-02 15:11 UTC
