### ISSUE TITLE
Wuxiaworld.site errors

### ISSUE THREAD

**Issue by aditseng** [JimmXinu/FanFicFare#734] opened 2021-09-17 20:32 UTC
https://wuxiaworld.site/novel/rise-of-humanity-novels gives an error

`'NoneType' object has no attribute 'i'`

**Comment by JimmXinu** [comment] 2021-09-17 22:06
Are you sure this isn't a duplicate of #729 ?

Are you using the current test version of FFF?

**Closed** 2021-09-30 16:50 UTC
