### ISSUE TITLE
[Bug] Unknown 'NoneType' object has no attribute 'text' on royalroad.com downloads/updates

### ISSUE THREAD

**Issue by Spy6137** [JimmXinu/FanFicFare#929] opened 2023-02-25 18:24 UTC
I never had an issue before, but now downloads/updates from royalroad fail and result in Unknown 'NoneType' object has no attribute 'text'.

A scraper issue, perhaps?

Any ideas for what I can do?

**Comment by Edocsil** [comment] 2023-02-25 18:32
I'm guessing this is a duplicate of #923.

**Comment by JimmXinu** [comment] 2023-02-25 18:33
Dup of #923.  And #925 and #926. #929

**Closed by JimmXinu** 2023-02-25 18:33 UTC
