### ISSUE TITLE
FanFiction blocking downloads again?

### ISSUE THREAD

**Issue by AndyHit5687** [JimmXinu/FanFicFare#639] opened 2021-01-21 15:10 UTC
I have just updated my Calibra pluging to 3.29 and am still blocked.

First error, now repeats.
cloudscraper reports: "Detected a Cloudflare version 2 challenge, This feature is not available...."

I got past this once but all downloaded chapters failed.

If it would help I can run in "debug" mode to obtain more info if you tell me how.

I am in the UK.

Thanks
Andy H

**Comment by AndyHit5687** [comment] 2021-01-21 15:39
Found how to start Calibra in debug, log follows:

FFF: DEBUG: 2021-01-21 15:33:02,089: calibre_plugins.fanficfare_plugin.fff_plugin(221): Plugin FanFicFare macmenuhack file_path:C:\Users\Andy\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
calibre Debug log
calibre 5.9 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: FanFicFare (3, 29, 0)
calibre 5.9 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: FanFicFare (3, 29, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 127.66492146596858 x 127.59069767441859
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.56] splash screen shown
[0.56] Initializing db...
[0.56] db initialized
[0.56] Constructing main UI...
[2.09] main UI initialized...
[2.09] Hiding splash screen
Starting QuickView
FFF: DEBUG: 2021-01-21 15:33:25,373: calibre_plugins.fanficfare_plugin.fff_plugin(1099): FanFicFare v3.29.0
FFF: DEBUG: 2021-01-21 15:33:25,453: calibre_plugins.fanficfare_plugin.fff_plugin(1220): prep_download_loop url:https://www.fanfiction.net/s/13600227/1/
FFF: INFO: 2021-01-21 15:33:25,454: calibre_plugins.fanficfare_plugin.prefs(218): Attempting to read settings from predecessor--FFDL
FFF: INFO: 2021-01-21 15:33:25,454: calibre_plugins.fanficfare_plugin.prefs(223): Using default settings
FFF: DEBUG: 2021-01-21 15:33:25,471: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1275): 
===========
 set sleep time 3.0
===========
FFF: DEBUG: 2021-01-21 15:33:25,471: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_fanfictionnet(100): URL: https://www.fanfiction.net/s/13600227/1/
FFF: DEBUG: 2021-01-21 15:33:25,471: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1209): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/s/13600227/1/
FFF: DEBUG: 2021-01-21 15:33:25,471: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1280): extra sleep:1.0
FFF: DEBUG: 2021-01-21 15:33:26,485: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1291): random sleep(1.50-4.50):3.67
FFF: DEBUG: 2021-01-21 15:33:30,162: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1249): Using cloudscraper for GET
FFF: DEBUG: 2021-01-21 15:33:30,308: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1331): Caught an exception reading URL: https://www.fanfiction.net/s/13600227/1/ sleeptime(0) Exception Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version..
FFF: ERROR: 2021-01-21 15:33:30,308: calibre_plugins.fanficfare_plugin.dialogs(723): Exception: {'title': 'The Ancient and Most Noble House of Potter', 'author_sort': 'Invieri', 'author': ['Invieri'], 'comments': '', 'good': False, 'status': 'Error', 'showerror': True, 'calibre_id': 38, 'begin': None, 'end': None, 'comment': 'cloudscraper reports: "Detected a Cloudflare version 2 challenge, This feature is not available...."', 'url': 'https://www.fanfiction.net/s/13600227/1/', 'site': 'www.fanfiction.net', 'series': '', 'added': False, 'pubdate': None, 'publisher': 'www.fanfiction.net', 'listorder': 0, 'collision': 'Overwrite if Newer'}:cloudscraper reports: "Detected a Cloudflare version 2 challenge, This feature is not available...."
Traceback (most recent call last):
cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
calibre_plugins.fanficfare_plugin.fanficfare.exceptions.FailedToDownload: cloudscraper reports: "Detected a Cloudflare version 2 challenge, This feature is not available...."
FFF: DEBUG: 2021-01-21 15:36:26,238: calibre_plugins.fanficfare_plugin.fff_plugin(1099): FanFicFare v3.29.0
FFF: DEBUG: 2021-01-21 15:36:26,329: calibre_plugins.fanficfare_plugin.fff_plugin(1220): prep_download_loop url:https://www.fanfiction.net/s/13600227/1/
FFF: DEBUG: 2021-01-21 15:36:26,346: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1275): 
===========
 set sleep time 3.0
===========
FFF: DEBUG: 2021-01-21 15:36:26,346: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_fanfictionnet(100): URL: https://www.fanfiction.net/s/13600227/1/
FFF: DEBUG: 2021-01-21 15:36:26,346: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1209): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/s/13600227/1/
FFF: DEBUG: 2021-01-21 15:36:26,346: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1280): extra sleep:1.0
FFF: DEBUG: 2021-01-21 15:36:27,353: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1291): random sleep(1.50-4.50):3.59
FFF: DEBUG: 2021-01-21 15:36:30,948: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1249): Using cloudscraper for GET
FFF: DEBUG: 2021-01-21 15:36:31,096: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1331): Caught an exception reading URL: https://www.fanfiction.net/s/13600227/1/ sleeptime(0) Exception Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version..
FFF: ERROR: 2021-01-21 15:36:31,097: calibre_plugins.fanficfare_plugin.dialogs(723): Exception: {'title': 'The Ancient and Most Noble House of Potter', 'author_sort': 'Invieri', 'author': ['Invieri'], 'comments': '', 'good': False, 'status': 'Error', 'showerror': True, 'calibre_id': 38, 'begin': None, 'end': None, 'comment': 'cloudscraper reports: "Detected a Cloudflare version 2 challenge, This feature is not available...."', 'url': 'https://www.fanfiction.net/s/13600227/1/', 'site': 'www.fanfiction.net', 'series': '', 'added': False, 'pubdate': None, 'publisher': 'www.fanfiction.net', 'listorder': 0, 'collision': 'Overwrite if Newer'}:cloudscraper reports: "Detected a Cloudflare version 2 challenge, This feature is not available...."
Traceback (most recent call last):
cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
calibre_plugins.fanficfare_plugin.fanficfare.exceptions.FailedToDownload: cloudscraper reports: "Detected a Cloudflare version 2 challenge, This feature is not available...."
FFF: DEBUG: 2021-01-21 15:36:43,175: calibre_plugins.fanficfare_plugin.fff_plugin(1099): FanFicFare v3.29.0
FFF: DEBUG: 2021-01-21 15:36:43,258: calibre_plugins.fanficfare_plugin.fff_plugin(1220): prep_download_loop url:https://www.fanfiction.net/s/13600227/1/
FFF: DEBUG: 2021-01-21 15:36:43,286: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1275): 
===========
 set sleep time 3.0
===========
FFF: DEBUG: 2021-01-21 15:36:43,286: calibre_plugins.fanficfare_plugin.fanficfare.adapters.adapter_fanfictionnet(100): URL: https://www.fanfiction.net/s/13600227/1/
FFF: DEBUG: 2021-01-21 15:36:43,287: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1209): #####################################
pagecache(GET) MISS: https://www.fanfiction.net/s/13600227/1/
FFF: DEBUG: 2021-01-21 15:36:43,287: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1280): extra sleep:1.0
FFF: DEBUG: 2021-01-21 15:36:44,289: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1291): random sleep(1.50-4.50):3.62
FFF: DEBUG: 2021-01-21 15:36:47,920: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1249): Using cloudscraper for GET
FFF: DEBUG: 2021-01-21 15:36:48,020: calibre_plugins.fanficfare_plugin.fanficfare.configurable(1331): Caught an exception reading URL: https://www.fanfiction.net/s/13600227/1/ sleeptime(0) Exception Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version..
FFF: ERROR: 2021-01-21 15:36:48,022: calibre_plugins.fanficfare_plugin.dialogs(723): Exception: {'title': 'The Ancient and Most Noble House of Potter', 'author_sort': 'Invieri', 'author': ['Invieri'], 'comments': '', 'good': False, 'status': 'Error', 'showerror': True, 'calibre_id': 38, 'begin': None, 'end': None, 'comment': 'cloudscraper reports: "Detected a Cloudflare version 2 challenge, This feature is not available...."', 'url': 'https://www.fanfiction.net/s/13600227/1/', 'site': 'www.fanfiction.net', 'series': '', 'added': False, 'pubdate': None, 'publisher': 'www.fanfiction.net', 'listorder': 0, 'collision': 'Overwrite if Newer'}:cloudscraper reports: "Detected a Cloudflare version 2 challenge, This feature is not available...."
Traceback (most recent call last):
cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
calibre_plugins.fanficfare_plugin.fanficfare.exceptions.FailedToDownload: cloudscraper reports: "Detected a Cloudflare version 2 challenge, This feature is not available...."
[16.55] splash screen hidden
[16.55] Started up in 16.55 seconds with 37 books

**Comment by JimmXinu** [comment] 2021-01-21 17:01
Duplicate of #637

**Closed by JimmXinu** 2021-01-21 17:01 UTC
