### ISSUE TITLE
'NoneType' object has no attribute 'decompose'

### ISSUE THREAD

**Issue by kyoam** [JimmXinu/FanFicFare#1021] opened 2023-11-29 08:58 UTC
new error preventing updates on two fics from spacebattles with the reason being 'NoneType' object has no attribute 'decompose'

these are the two stories 

https://forums.spacebattles.com/threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/
https://forums.spacebattles.com/threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/

and this is the debug log:

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
EpubMerge: DEBUG: 2023-11-29 03:52:22,736: calibre_plugins.epubmerge.epubmerge_plugin(156): macmenuhack file_path:C:\Users\Owner\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
FFF: DEBUG: 2023-11-29 03:52:22,750: calibre_plugins.fanficfare_plugin.fff_plugin(215): Plugin FanFicFare macmenuhack file_path:C:\Users\Owner\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
calibre Debug log
calibre 7.1  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: EpubMerge (2, 16, 0) && FanFicFare (4, 29, 0)
calibre 7.1  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: EpubMerge (2, 16, 0) && FanFicFare (4, 29, 0)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 135.46666666666664 x 135.46666666666664
[0.00] Starting up...
[0.00] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[1.50] db initialized
[1.50] Constructing main UI...
[6.08] main UI initialized...
[6.08] Hiding splash screen
Starting QuickView
FFF: DEBUG: 2023-11-29 03:52:29,617: story.py(737): use_flaresolverr_proxy:
FFF: DEBUG: 2023-11-29 03:52:56,425: calibre_plugins.fanficfare_plugin.dialogs(493): self.extraoptions['anthology_url']:NOT FOUND
FFF: DEBUG: 2023-11-29 03:52:56,425: story.py(737): use_flaresolverr_proxy:
FFF: DEBUG: 2023-11-29 03:52:56,425: story.py(737): use_flaresolverr_proxy:
FFF: DEBUG: 2023-11-29 03:52:56,425: calibre_plugins.fanficfare_plugin.fff_plugin(1125): FanFicFare v4.29.0
FFF: INFO: 2023-11-29 03:52:56,526: calibre_plugins.fanficfare_plugin.prefs(216): Using default settings
FFF: DEBUG: 2023-11-29 03:52:56,526: story.py(737): use_flaresolverr_proxy:
FFF: DEBUG: 2023-11-29 03:52:56,542: configurable.py(1078): use_browser_cache:
FFF: DEBUG: 2023-11-29 03:52:56,542: configurable.py(1098): use_basic_cache:true
FFF: INFO: 2023-11-29 03:52:56,542: base_xenforoforum_adapter.py(451): url: https://forums.spacebattles.com/threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/
FFF: DEBUG: 2023-11-29 03:52:56,542: cache_basic.py(116): 
========== MISS (GET) BasicCache
https://forums.spacebattles.com/threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/
FFF: DEBUG: 2023-11-29 03:52:56,542: fetcher_requests.py(114): 
---------- REQ (GET) RequestsFetcher
https://forums.spacebattles.com/threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/
FFF: DEBUG: 2023-11-29 03:52:57,254: fetcher_requests.py(127): response code:200
FFF: DEBUG: 2023-11-29 03:52:57,254: decorators.py(112): fromcache:False
FFF: DEBUG: 2023-11-29 03:52:57,254: decorators.py(123): random sleep(1.00-3.00):2.74
FFF: DEBUG: 2023-11-29 03:52:59,998: requestable.py(55): Encoding:utf8
FFF: INFO: 2023-11-29 03:52:59,998: base_xenforoforum_adapter.py(455): use useurl: https://forums.spacebattles.com/threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/
FFF: DEBUG: 2023-11-29 03:53:00,359: cache_basic.py(116): 
========== MISS (GET) BasicCache
https://forums.spacebattles.com/threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/threadmarks
FFF: DEBUG: 2023-11-29 03:53:00,359: fetcher_requests.py(114): 
---------- REQ (GET) RequestsFetcher
https://forums.spacebattles.com/threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/threadmarks
FFF: DEBUG: 2023-11-29 03:53:00,470: fetcher_requests.py(127): response code:200
FFF: DEBUG: 2023-11-29 03:53:00,470: decorators.py(112): fromcache:False
FFF: DEBUG: 2023-11-29 03:53:00,470: decorators.py(123): random sleep(1.00-3.00):2.98
FFF: DEBUG: 2023-11-29 03:53:03,460: requestable.py(55): Encoding:utf8
FFF: DEBUG: 2023-11-29 03:53:03,596: cache_basic.py(116): 
========== MISS (GET) BasicCache
https://forums.spacebattles.com/threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/threadmarks?threadmark_category=16
FFF: DEBUG: 2023-11-29 03:53:03,596: fetcher_requests.py(114): 
---------- REQ (GET) RequestsFetcher
https://forums.spacebattles.com/threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/threadmarks?threadmark_category=16
FFF: DEBUG: 2023-11-29 03:53:03,706: fetcher_requests.py(127): response code:200
FFF: DEBUG: 2023-11-29 03:53:03,706: decorators.py(112): fromcache:False
FFF: DEBUG: 2023-11-29 03:53:03,706: decorators.py(123): random sleep(1.00-3.00):2.66
FFF: DEBUG: 2023-11-29 03:53:06,374: requestable.py(55): Encoding:utf8
FFF: DEBUG: 2023-11-29 03:53:06,469: cache_basic.py(116): 
========== MISS (GET) BasicCache
https://forums.spacebattles.com/threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/threadmarks?threadmark_category=13
FFF: DEBUG: 2023-11-29 03:53:06,469: fetcher_requests.py(114): 
---------- REQ (GET) RequestsFetcher
https://forums.spacebattles.com/threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/threadmarks?threadmark_category=13
FFF: DEBUG: 2023-11-29 03:53:06,612: fetcher_requests.py(127): response code:200
FFF: DEBUG: 2023-11-29 03:53:06,612: decorators.py(112): fromcache:False
FFF: DEBUG: 2023-11-29 03:53:06,612: decorators.py(123): random sleep(1.00-3.00):2.99
FFF: DEBUG: 2023-11-29 03:53:09,598: requestable.py(55): Encoding:utf8
FFF: DEBUG: 2023-11-29 03:53:09,985: cache_basic.py(116): 
========== MISS (GET) BasicCache
https://forums.spacebattles.com//threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/threadmarks-load-range?threadmark_category_id=13&min=96&max=103
FFF: DEBUG: 2023-11-29 03:53:09,985: fetcher_requests.py(114): 
---------- REQ (GET) RequestsFetcher
https://forums.spacebattles.com//threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/threadmarks-load-range?threadmark_category_id=13&min=96&max=103
FFF: DEBUG: 2023-11-29 03:53:10,080: fetcher_requests.py(127): response code:200
FFF: DEBUG: 2023-11-29 03:53:10,080: decorators.py(112): fromcache:False
FFF: DEBUG: 2023-11-29 03:53:10,080: decorators.py(123): random sleep(1.00-3.00):1.91
FFF: DEBUG: 2023-11-29 03:53:11,999: requestable.py(55): Encoding:utf8
FFF: DEBUG: 2023-11-29 03:53:12,076: cache_basic.py(116): 
========== MISS (GET) BasicCache
https://forums.spacebattles.com/threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/threadmarks?threadmark_category=10
FFF: DEBUG: 2023-11-29 03:53:12,076: fetcher_requests.py(114): 
---------- REQ (GET) RequestsFetcher
https://forums.spacebattles.com/threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/threadmarks?threadmark_category=10
FFF: DEBUG: 2023-11-29 03:53:12,200: fetcher_requests.py(127): response code:200
FFF: DEBUG: 2023-11-29 03:53:12,200: decorators.py(112): fromcache:False
FFF: DEBUG: 2023-11-29 03:53:12,200: decorators.py(123): random sleep(1.00-3.00):2.32
FFF: DEBUG: 2023-11-29 03:53:14,522: requestable.py(55): Encoding:utf8
FFF: DEBUG: 2023-11-29 03:53:14,759: cache_basic.py(116): 
========== MISS (GET) BasicCache
https://forums.spacebattles.com/threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/threadmarks?threadmark_category=19
FFF: DEBUG: 2023-11-29 03:53:14,759: fetcher_requests.py(114): 
---------- REQ (GET) RequestsFetcher
https://forums.spacebattles.com/threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/threadmarks?threadmark_category=19
FFF: DEBUG: 2023-11-29 03:53:14,885: fetcher_requests.py(127): response code:200
FFF: DEBUG: 2023-11-29 03:53:14,885: decorators.py(112): fromcache:False
FFF: DEBUG: 2023-11-29 03:53:14,885: decorators.py(123): random sleep(1.00-3.00):2.80
FFF: DEBUG: 2023-11-29 03:53:17,683: requestable.py(55): Encoding:utf8
FFF: ERROR: 2023-11-29 03:53:18,254: calibre_plugins.fanficfare_plugin.dialogs(725): Exception: {'title': 'Unknown', 'author_sort': ['Unknown'], 'author': ['Unknown'], 'comments': '', 'good': False, 'status': 'Error', 'showerror': True, 'calibre_id': None, 'begin': None, 'end': None, 'comment': "'NoneType' object has no attribute 'decompose'", 'url': 'https://forums.spacebattles.com/threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/', 'site': 'forums.spacebattles.com', 'series': '', 'added': False, 'pubdate': None, 'publisher': None, 'uniqueurl': 'https://forums.spacebattles.com/threads/fleet-of-the-homeward-bound-sci-fi-shipgirl-multicross.896133/[None-None]', 'listorder': 0, 'collision': 'Add New Book'}:'NoneType' object has no attribute 'decompose'
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.dialogs", line 712, in do_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1331, in prep_download_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1211, in get_story_metadata_only
  File "C:\Users\Owner\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_adapter.py", line 331, in getStoryMetadataOnly
  File "C:\Users\Owner\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_adapter.py", line 435, in doExtractChapterUrlsAndMetadata
  File "C:\Users\Owner\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_xenforoforum_adapter.py", line 554, in extractChapterUrlsAndMetadata
  File "C:\Users\Owner\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_xenforo2forum_adapter.py", line 113, in set_threadmarks_metadata
AttributeError: 'NoneType' object has no attribute 'decompose'
FFF: DEBUG: 2023-11-29 03:53:18,390: story.py(737): use_flaresolverr_proxy:
FFF: DEBUG: 2023-11-29 03:53:18,397: configurable.py(1078): use_browser_cache:
FFF: DEBUG: 2023-11-29 03:53:18,397: configurable.py(1098): use_basic_cache:true
FFF: INFO: 2023-11-29 03:53:18,397: base_xenforoforum_adapter.py(451): url: https://forums.spacebattles.com/threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/
FFF: DEBUG: 2023-11-29 03:53:18,397: cache_basic.py(116): 
========== MISS (GET) BasicCache
https://forums.spacebattles.com/threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/
FFF: DEBUG: 2023-11-29 03:53:18,397: fetcher_requests.py(114): 
---------- REQ (GET) RequestsFetcher
https://forums.spacebattles.com/threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/
FFF: DEBUG: 2023-11-29 03:53:19,187: fetcher_requests.py(127): response code:200
FFF: DEBUG: 2023-11-29 03:53:19,187: decorators.py(112): fromcache:False
FFF: DEBUG: 2023-11-29 03:53:19,187: decorators.py(123): random sleep(1.00-3.00):2.45
FFF: DEBUG: 2023-11-29 03:53:21,653: requestable.py(55): Encoding:utf8
FFF: INFO: 2023-11-29 03:53:21,653: base_xenforoforum_adapter.py(455): use useurl: https://forums.spacebattles.com/threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/
FFF: DEBUG: 2023-11-29 03:53:22,271: cache_basic.py(116): 
========== MISS (GET) BasicCache
https://forums.spacebattles.com/threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/threadmarks
FFF: DEBUG: 2023-11-29 03:53:22,271: fetcher_requests.py(114): 
---------- REQ (GET) RequestsFetcher
https://forums.spacebattles.com/threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/threadmarks
FFF: DEBUG: 2023-11-29 03:53:22,382: fetcher_requests.py(127): response code:200
FFF: DEBUG: 2023-11-29 03:53:22,382: decorators.py(112): fromcache:False
FFF: DEBUG: 2023-11-29 03:53:22,382: decorators.py(123): random sleep(1.00-3.00):1.75
FFF: DEBUG: 2023-11-29 03:53:24,148: requestable.py(55): Encoding:utf8
FFF: DEBUG: 2023-11-29 03:53:24,575: cache_basic.py(116): 
========== MISS (GET) BasicCache
https://forums.spacebattles.com//threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/threadmarks-load-range?threadmark_category_id=1&min=96&max=99
FFF: DEBUG: 2023-11-29 03:53:24,575: fetcher_requests.py(114): 
---------- REQ (GET) RequestsFetcher
https://forums.spacebattles.com//threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/threadmarks-load-range?threadmark_category_id=1&min=96&max=99
FFF: DEBUG: 2023-11-29 03:53:24,670: fetcher_requests.py(127): response code:200
FFF: DEBUG: 2023-11-29 03:53:24,670: decorators.py(112): fromcache:False
FFF: DEBUG: 2023-11-29 03:53:24,670: decorators.py(123): random sleep(1.00-3.00):1.45
FFF: DEBUG: 2023-11-29 03:53:26,139: requestable.py(55): Encoding:utf8
FFF: DEBUG: 2023-11-29 03:53:26,201: cache_basic.py(116): 
========== MISS (GET) BasicCache
https://forums.spacebattles.com/threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/threadmarks?threadmark_category=16
FFF: DEBUG: 2023-11-29 03:53:26,201: fetcher_requests.py(114): 
---------- REQ (GET) RequestsFetcher
https://forums.spacebattles.com/threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/threadmarks?threadmark_category=16
FFF: DEBUG: 2023-11-29 03:53:26,296: fetcher_requests.py(127): response code:200
FFF: DEBUG: 2023-11-29 03:53:26,296: decorators.py(112): fromcache:False
FFF: DEBUG: 2023-11-29 03:53:26,296: decorators.py(123): random sleep(1.00-3.00):2.46
FFF: DEBUG: 2023-11-29 03:53:28,753: requestable.py(55): Encoding:utf8
FFF: DEBUG: 2023-11-29 03:53:28,891: cache_basic.py(116): 
========== MISS (GET) BasicCache
https://forums.spacebattles.com/threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/threadmarks?threadmark_category=13
FFF: DEBUG: 2023-11-29 03:53:28,891: fetcher_requests.py(114): 
---------- REQ (GET) RequestsFetcher
https://forums.spacebattles.com/threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/threadmarks?threadmark_category=13
FFF: DEBUG: 2023-11-29 03:53:28,986: fetcher_requests.py(127): response code:200
FFF: DEBUG: 2023-11-29 03:53:28,986: decorators.py(112): fromcache:False
FFF: DEBUG: 2023-11-29 03:53:28,986: decorators.py(123): random sleep(1.00-3.00):1.80
FFF: DEBUG: 2023-11-29 03:53:30,804: requestable.py(55): Encoding:utf8
FFF: DEBUG: 2023-11-29 03:53:30,859: cache_basic.py(116): 
========== MISS (GET) BasicCache
https://forums.spacebattles.com/threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/threadmarks?threadmark_category=10
FFF: DEBUG: 2023-11-29 03:53:30,859: fetcher_requests.py(114): 
---------- REQ (GET) RequestsFetcher
https://forums.spacebattles.com/threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/threadmarks?threadmark_category=10
FFF: DEBUG: 2023-11-29 03:53:30,969: fetcher_requests.py(127): response code:200
FFF: DEBUG: 2023-11-29 03:53:30,969: decorators.py(112): fromcache:False
FFF: DEBUG: 2023-11-29 03:53:30,969: decorators.py(123): random sleep(1.00-3.00):2.77
FFF: DEBUG: 2023-11-29 03:53:33,747: requestable.py(55): Encoding:utf8
FFF: DEBUG: 2023-11-29 03:53:33,787: cache_basic.py(116): 
========== MISS (GET) BasicCache
https://forums.spacebattles.com/threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/threadmarks?threadmark_category=19
FFF: DEBUG: 2023-11-29 03:53:33,787: fetcher_requests.py(114): 
---------- REQ (GET) RequestsFetcher
https://forums.spacebattles.com/threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/threadmarks?threadmark_category=19
FFF: DEBUG: 2023-11-29 03:53:33,897: fetcher_requests.py(127): response code:200
FFF: DEBUG: 2023-11-29 03:53:33,897: decorators.py(112): fromcache:False
FFF: DEBUG: 2023-11-29 03:53:33,897: decorators.py(123): random sleep(1.00-3.00):2.92
FFF: DEBUG: 2023-11-29 03:53:36,816: requestable.py(55): Encoding:utf8
FFF: ERROR: 2023-11-29 03:53:37,048: calibre_plugins.fanficfare_plugin.dialogs(725): Exception: {'title': 'Unknown', 'author_sort': ['Unknown'], 'author': ['Unknown'], 'comments': '', 'good': False, 'status': 'Error', 'showerror': True, 'calibre_id': None, 'begin': None, 'end': None, 'comment': "'NoneType' object has no attribute 'decompose'", 'url': 'https://forums.spacebattles.com/threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/', 'site': 'forums.spacebattles.com', 'series': '', 'added': False, 'pubdate': None, 'publisher': None, 'uniqueurl': 'https://forums.spacebattles.com/threads/save-scumming-its-on-my-character-sheet-re-zero-fate-grand-order.828712/[None-None]', 'listorder': 1, 'collision': 'Add New Book'}:'NoneType' object has no attribute 'decompose'
Traceback (most recent call last):
  File "calibre_plugins.fanficfare_plugin.dialogs", line 712, in do_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1331, in prep_download_loop
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 1211, in get_story_metadata_only
  File "C:\Users\Owner\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_adapter.py", line 331, in getStoryMetadataOnly
  File "C:\Users\Owner\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_adapter.py", line 435, in doExtractChapterUrlsAndMetadata
  File "C:\Users\Owner\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_xenforoforum_adapter.py", line 554, in extractChapterUrlsAndMetadata
  File "C:\Users\Owner\AppData\Roaming\calibre\plugins\FanFicFare.zip\fanficfare\adapters\base_xenforo2forum_adapter.py", line 113, in set_threadmarks_metadata
AttributeError: 'NoneType' object has no attribute 'decompose'

so far these are the only two this happens in and the error did not show up on the sufficient velocity versions of each fic.

**Comment by JimmXinu** [comment] 2023-11-29 15:15
Duplicate of #1017

**Closed by JimmXinu** 2023-11-29 15:15 UTC
