### ISSUE TITLE
SpaceBattles and Sufficient Velocity downloads not working

### ISSUE THREAD

**Issue by JTBlum** [JimmXinu/FanFicFare#282] opened 2018-03-27 19:59 UTC
It's only been this way for a few days, but both forums seem to be only downloading the latest threadmarks now even if I try to give FFFare the URL in reader mode or with the threadmark index. This is reproducible with the following thread:

https://forums.sufficientvelocity.com/threads/i-am-skitter-worm.30884/

The URLs I've tried are the one above and those below, which have worked for me in the past. I think they updated their sites.

https://forums.sufficientvelocity.com/threads/i-am-skitter-worm.30884/threadmarks?category_id=1
https://forums.sufficientvelocity.com/threads/i-am-skitter-worm.30884/reader
https://forums.spacebattles.com/threads/i-am-skitter-worm.410333/threadmarks?category_id=1
https://forums.spacebattles.com/threads/i-am-skitter-worm.410333/reader

**Comment by JimmXinu** [comment] 2018-03-27 20:08
Duplicate of #278,  #279 and #281.  Fixed test version was out over a week ago and released version earlier today.

**Closed by JimmXinu** 2018-03-27 20:08 UTC
